name: Sync to DigitalOcean Spaces

on:
  push:
    branches:
      - master

jobs:
  sync-to-spaces:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: 'ecc-mvn-repo'
          AWS_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_ACCESS_KEY }}
          AWS_S3_ENDPOINT: 'https://ams3.digitaloceanspaces.com'
